# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.2
default_acceleration_scaling_factor: 0.2

# Joints limits
#
# arm_ prefixed version from _description/config/joint_limits.yaml
# only required because acceleration limits are not specified in the URDF
# position range and velocity limits could also be further reduced here
joint_limits:
  arm_shoulder_pan:
    max_acceleration: !degrees 720.0
  arm_shoulder_lift:
    max_acceleration: !degrees 720.0
  arm_elbow_joint:
    max_acceleration: !degrees 720.0
  arm_wrist_1:
    max_acceleration: !degrees 720.0
  arm_wrist_2:
    max_acceleration: !degrees 720.0
  arm_wrist_3:
    max_acceleration: !degrees 720.0
