# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.2
default_acceleration_scaling_factor: 1.0

# Joints limits
#
# arm_*_joint version from _description/config/joint_limits.yaml adapted for MoveIt
# only required because acceleration limits are not specified in the URDF
# joint range and velocity limits could also be further reduced here
# The Pilz' planner can read additional jerk and deceleration limits from here as well
joint_limits:
  arm_shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: !degrees 360.0
  arm_shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: !degrees 360.0
  arm_elbow_joint:
    has_acceleration_limits: true
    max_acceleration: !degrees 360.0
  arm_wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: !degrees 360.0
  arm_wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: !degrees 360.0
  arm_wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: !degrees 360.0
