arm:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_timeout: 0.005
  goal_joint_tolerance: 0.0001
  goal_position_tolerance: 0.0001
  goal_orientation_tolerance: 0.001

arm_local:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_timeout: 0.005
  goal_joint_tolerance: 0.0001
  goal_position_tolerance: 0.0001
  goal_orientation_tolerance: 0.001
  mode: gd_c
