<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="cu_ur5e">
    <xacro:include filename="$(find ur_description)/urdf/inc/ur5e_macro.xacro" />

    <xacro:ur5e_robot
        prefix="arm_"
        joint_limits_parameters_file="$(find cu_ur5e_description)/config/joint_limits.yaml"
        kinematics_parameters_file="$(find cu_ur5e_description)/config/kinematics_parameters.yaml"
        safety_limits="true"
        />

    <xacro:property name="mount_height" value="0.8"/>
    <link name="mount">
        <visual>
            <geometry>
                <cylinder length="${mount_height}" radius="0.07"/>
            </geometry>
            <origin xyz="0 0 ${mount_height / 2}" rpy="0 0 0"/>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1"/>
            </material>
        </visual>
        <visual>
            <geometry>
                <cylinder length="0.013" radius="0.1" />
            </geometry>
            <origin xyz="0 0 ${mount_height - 0.0065}" rpy="0 0 0"/>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1"/>
            </material>
        </visual>
        <visual>
            <geometry>
                <box size="1.0 0.05 0.05"/>
            </geometry>
            <origin xyz="0 0 ${0 + 0.025}" rpy="0 0 ${tau/4}"/>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1"/>
            </material>
        </visual>
        <visual>
            <geometry>
                <box size="1.0 0.05 0.05"/>
            </geometry>
            <origin xyz="0 0 ${0 + 0.025}" rpy="0 0 ${tau/4+tau/6}"/>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1"/>
            </material>
        </visual>
        <visual>
            <geometry>
                <box size="1.0 0.05 0.05"/>
            </geometry>
            <origin xyz="0 0 ${0 + 0.025}" rpy="0 0 ${tau/4-tau/6}"/>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${mount_height}" radius="0.15"/>
            </geometry>
            <origin xyz="0 0 ${mount_height / 2}" rpy="0 0 0"/>
        </collision>
    </link>
    <joint name="mount_to_arm_base" type="fixed">
        <parent link="mount"/>
        <child link="arm_base_link"/>
        <origin xyz="0 0 ${mount_height}" rpy="0 0 ${-tau/4}"/>
    </joint>

    <link name="base" />
    <joint name="base_to_mount" type="fixed">
        <parent link="base"/>
        <child link="mount"/>
        <origin xyz="0 0 0.0" rpy="0 0 0"/>
    </joint>

    <link name="control_box">
        <visual>
            <geometry>
                <box size="0.32 0.6 0.5"/>
            </geometry>
            <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.32 0.6 0.5"/>
            </geometry>
            <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
        </collision>
    </link>
    <joint name="mount_to_control_box" type="fixed">
        <parent link="mount"/>
        <child link="control_box"/>
        <origin xyz="-0.3 0.0 0.5" rpy="0 0 0"/>
    </joint>

    <link name="wall">
        <visual>
            <geometry>
                <box size="0.1 4.0 2.0"/>
            </geometry>
            <origin xyz="0 0 1.0" rpy="0 0 0"/>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 4.0 2.0"/>
            </geometry>
            <origin xyz="0 0 1.0" rpy="0 0 0"/>
        </collision>
    </link>
    <joint name="base_to_wall" type="fixed">
        <parent link="base"/>
        <child link="wall"/>
        <origin xyz="-.5 0 0" rpy="0 0 0"/>
    </joint>
</robot>